[2022-09-21 00:00:07,710] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 00:00:07,722] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 00:00:07,722] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 00:00:07,722] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-21 00:00:07,722] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 00:00:07,734] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_green_tripdata_partitioned_table_task> on 2022-09-20 00:00:00+00:00
[2022-09-21 00:00:07,742] {standard_task_runner.py:52} INFO - Started process 23331 to run task
[2022-09-21 00:00:07,748] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_green_tripdata_partitioned_table_task', 'scheduled__2022-09-20T00:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmpu1az4wz9', '--error-file', '/tmp/tmp0m0bb7oz']
[2022-09-21 00:00:07,749] {standard_task_runner.py:77} INFO - Job 199: Subtask bq_create_green_tripdata_partitioned_table_task
[2022-09-21 00:00:07,817] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [running]> on host 788dccad41b9
[2022-09-21 00:00:07,880] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_green_tripdata_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-20T00:00:00+00:00
[2022-09-21 00:00:07,882] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-09-21 00:00:07,883] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-21 00:00:07,892] {bigquery.py:1637} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_195891d56ceb7c8cdbd9db32b638acef
[2022-09-21 00:00:10,589] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64. File: gs://tez-bucket/green/green_tripdata/2019/green_tripdata_2019-03.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_195891d56ceb7c8cdbd9db32b638acef)

                                                                                  -----Query Job SQL Follows-----                                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.green_tripdata             PARTITION BY DATE(lpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.green_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 00:00:10,615] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_create_green_tripdata_partitioned_table_task, execution_date=20220920T000000, start_date=20220921T000007, end_date=20220921T000010
[2022-09-21 00:00:10,632] {standard_task_runner.py:92} ERROR - Failed to execute job 199 for task bq_create_green_tripdata_partitioned_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64. File: gs://tez-bucket/green/green_tripdata/2019/green_tripdata_2019-03.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_195891d56ceb7c8cdbd9db32b638acef)

                                                                                  -----Query Job SQL Follows-----                                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.green_tripdata             PARTITION BY DATE(lpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.green_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 00:00:10,651] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-21 00:00:10,701] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-21 01:37:22,822] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 01:37:22,841] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 01:37:22,841] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 01:37:22,841] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-21 01:37:22,841] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 01:37:22,857] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_green_tripdata_partitioned_table_task> on 2022-09-20 00:00:00+00:00
[2022-09-21 01:37:22,865] {standard_task_runner.py:52} INFO - Started process 28304 to run task
[2022-09-21 01:37:22,872] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_green_tripdata_partitioned_table_task', 'scheduled__2022-09-20T00:00:00+00:00', '--job-id', '367', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmpncjw4q2i', '--error-file', '/tmp/tmpm_992rjs']
[2022-09-21 01:37:22,873] {standard_task_runner.py:77} INFO - Job 367: Subtask bq_create_green_tripdata_partitioned_table_task
[2022-09-21 01:37:22,938] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [running]> on host 788dccad41b9
[2022-09-21 01:37:23,015] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_green_tripdata_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-20T00:00:00+00:00
[2022-09-21 01:37:23,018] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-09-21 01:37:23,019] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-21 01:37:23,034] {bigquery.py:1637} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_de4ead39434685e5f2c78935785d5c20
[2022-09-21 01:37:25,892] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64. File: gs://tez-bucket/green/green_tripdata/2019/green_tripdata_2019-04.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_de4ead39434685e5f2c78935785d5c20)

                                                                                  -----Query Job SQL Follows-----                                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.green_tripdata             PARTITION BY DATE(lpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.green_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 01:37:25,914] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_create_green_tripdata_partitioned_table_task, execution_date=20220920T000000, start_date=20220921T013722, end_date=20220921T013725
[2022-09-21 01:37:25,932] {standard_task_runner.py:92} ERROR - Failed to execute job 367 for task bq_create_green_tripdata_partitioned_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64. File: gs://tez-bucket/green/green_tripdata/2019/green_tripdata_2019-04.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_de4ead39434685e5f2c78935785d5c20)

                                                                                  -----Query Job SQL Follows-----                                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.green_tripdata             PARTITION BY DATE(lpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.green_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 01:37:25,979] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-21 01:37:26,015] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
