[2022-09-21 01:53:52,411] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag_copy.move_files_gcs_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 01:53:52,422] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag_copy.move_files_gcs_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 01:53:52,422] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 01:53:52,422] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-21 01:53:52,422] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 01:53:52,434] {taskinstance.py:1259} INFO - Executing <Task(GCSToGCSOperator): move_files_gcs_task> on 2022-09-20 00:00:00+00:00
[2022-09-21 01:53:52,441] {standard_task_runner.py:52} INFO - Started process 29038 to run task
[2022-09-21 01:53:52,445] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag_copy', 'move_files_gcs_task', 'scheduled__2022-09-20T00:00:00+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag copy.py', '--cfg-path', '/tmp/tmp56dkdhsj', '--error-file', '/tmp/tmpydamqfem']
[2022-09-21 01:53:52,446] {standard_task_runner.py:77} INFO - Job 371: Subtask move_files_gcs_task
[2022-09-21 01:53:52,508] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag_copy.move_files_gcs_task scheduled__2022-09-20T00:00:00+00:00 [running]> on host 788dccad41b9
[2022-09-21 01:53:52,567] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag_copy
AIRFLOW_CTX_TASK_ID=move_files_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-20T00:00:00+00:00
[2022-09-21 01:53:52,569] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-09-21 01:53:52,586] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 274, in execute
    self._copy_source_with_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 345, in _copy_source_with_wildcard
    raise AirflowException(error_msg)
airflow.exceptions.AirflowException: Only one wildcard '*' is allowed in source_object parameter. Found 2 in raw/yellow_tripdata*.parquet*.
[2022-09-21 01:53:52,595] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag_copy, task_id=move_files_gcs_task, execution_date=20220920T000000, start_date=20220921T015352, end_date=20220921T015352
[2022-09-21 01:53:52,609] {standard_task_runner.py:92} ERROR - Failed to execute job 371 for task move_files_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 274, in execute
    self._copy_source_with_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 345, in _copy_source_with_wildcard
    raise AirflowException(error_msg)
airflow.exceptions.AirflowException: Only one wildcard '*' is allowed in source_object parameter. Found 2 in raw/yellow_tripdata*.parquet*.
[2022-09-21 01:53:52,657] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-21 01:53:52,700] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
